export const SET_USER = 'SET_USER'

export const SET_USERS = 'SET_USERS'
export const NEW_USER = 'NEW_USER'
export const GET_USERS = 'GET_USERS'
export const GET_USER = 'GET_USER'
export const REGISTER_ERROR = 'REGISTER_ERROR'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'

export const SET_QUIZ = 'SET_QUIZ'
export const SET_QUIZZES = 'SET_QUIZZES'
export const GET_QUIZZES = 'GET_QUIZZES'

export const SET_QUESTION = 'SET_QUESTION'
export const SET_QUESTIONS = 'SET_QUESTIONS'

export const SCORE = 'SCORE'
export const OK = 'OK'

export const CHECK_GAME_TRUE = 'CHECK_GAME_TRUE'
export const CHECK_GAME_FALSE = 'CHECK_GAME_FALSE'
export const JOIN_GAME = 'JOIN_GAME'
export const GAME_STARTED = 'GAME_STARTED'
export const SET_GAME_LOADING = 'SET_GAME_LOADING'
export const SET_GAME = 'SET_GAME'
export const SET_GAME_ONLY = 'SET_GAME_ONLY'
export const SET_GAMES = 'SET_GAMES'
export const GET_GAMES = 'GET_GAMES'
export const SET_GAME_QUIZ = 'SET_GAME_QUIZ'
export const GET_GAMES_PLAYED = 'GET_GAMES_PLAYED'
